# Default values for loft.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Default value is: loftsh/loft:{{ .Chart.Version }}
# image: loftsh/loft

admin:
  create: true
  username: admin
  name: admin
  password: "" # leave empty to generate password reset link
  resetPassword: false
  accessKeySecret: loft-user-accesskey-admin

ingress:
  enabled: true
  name: loft-ingress
  host: loft.mydomain.tld
  path: /
  tls:
    enabled: true
    secret: tls-loft
    clusterIssuer: loft-letsencrypt-issuer

service:
  type: ClusterIP
  manager:
    port: 80
    targetPort: 8080

replicaCount: 1

resources:
  requests:
    memory: 128Mi
    cpu: 50m

apiService:
  enabled: true

serviceAccount:
  name: loft
  create: true
  clusterRole: cluster-admin

nameOverride: ""
fullnameOverride: ""

nginx-ingress:
  enabled: true

cert-manager:
  enabled: true
  issuer:
    create: true
    name: loft-letsencrypt-issuer
    secretName: loft-letsencrypt-credentials
    server: https://acme-v02.api.letsencrypt.org/directory
    httpResolver:
      enabled: true
      ingressClass: nginx
    resolvers: []