{{- if not (lookup "apiextensions.k8s.io/v1beta1" "CustomResourceDefinition" "" "clusteraccounttemplates.storage.loft.sh") }}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusteraccounttemplates.storage.loft.sh
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: pre-install,pre-upgrade
spec:
  conversion:
    strategy: None
  group: storage.loft.sh
  names:
    kind: ClusterAccountTemplate
    listKind: ClusterAccountTemplateList
    plural: clusteraccounttemplates
    singular: clusteraccounttemplate
  preserveUnknownFields: true
  scope: Cluster
  subresources:
    status: {}
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
{{- end }}