apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "loft.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "loft.fullname" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "loft.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ template "loft.serviceAccountName" . }}
      containers:
      - name: manager
        {{- if .Values.image }}
        image: "{{ .Values.image }}"
        {{- else }}
        image: "loftsh/loft:{{ .Chart.Version }}"
        {{- end }}
        {{- if .Values.livenessProbe }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /version
            port: 8080
            {{- if .Values.useSelfSignedCertificate }}
            scheme: HTTPS
            {{- end }}
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- end }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /version
            port: 8080
            {{- if .Values.useSelfSignedCertificate }}
            scheme: HTTPS
            {{- end }}
          failureThreshold: 6
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- end }}
        {{- end }}
        env:
        {{- if not .Values.apiService.enabled }}
        - name: APISERVICE_DISABLED
          value: "true"
        {{- end }}
        {{- if .Values.useSelfSignedCertificate }}
        - name: PROXY_TLS_SELF_SIGNED
          value: "true"
        {{- end }}
        {{- range $key, $value := .Values.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
