apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "loft.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "loft.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "loft.fullname" . }}
      release: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "loft.fullname" . }}
        release: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 10
      serviceAccountName: {{ template "loft.serviceAccountName" . }}
      {{- if .Values.volumes }}
      volumes:
{{ toYaml .Values.volumes | indent 8 }}
      {{- end }}
      containers:
      - name: manager
        {{- if .Values.image }}
        image: "{{ .Values.image }}"
        {{- else }}
        image: "loftsh/loft:{{ .Chart.Version }}"
        {{- end }}
        ports:
        - name: http
          containerPort: 80
        - name: https
          containerPort: 443
        {{- if .Values.livenessProbe }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 80
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- end }}
        {{- end }}
        {{- if .Values.readinessProbe }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /healthz
            port: 80
          failureThreshold: 10
          initialDelaySeconds: 5
          periodSeconds: 10
        {{- end }}
        {{- end }}
        env:
        {{- if .Values.tls }}
        {{- if .Values.tls.enabled }}
        - name: PROXY_TLS_CERT
          valueFrom:
            secretKeyRef:
              name: {{ .Values.tls.secret }}
              key: {{ .Values.tls.crtKey }}
        - name: PROXY_TLS_KEY
          valueFrom:
            secretKeyRef:
              name: {{ .Values.tls.secret }}
              key: {{ .Values.tls.keyKey }}
        {{- end }}
        {{- end }}
        {{- if not .Values.apiService.enabled }}
        - name: APISERVICE_DISABLED
          value: "true"
        {{- end }}
        {{- range $key, $value := .Values.env }}
        - name: {{ $key | quote }}
          value: {{ $value | quote }}
        {{- end }}
        {{- if .Values.volumeMounts }}
        volumeMounts:
{{ toYaml .Values.volumeMounts | indent 10 }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
