{{- if .Values.cluster.connect.local }}
apiVersion: storage.loft.sh/v1
kind: Cluster
metadata:
  name: local
  annotations:
    helm.sh/resource-policy: keep
    helm.sh/hook: pre-install
spec:
  local: true
{{- end }}