apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: clusteraccounttemplates.storage.loft.sh
spec:
  conversion:
    strategy: None
  group: storage.loft.sh
  names:
    kind: ClusterAccountTemplate
    listKind: ClusterAccountTemplateList
    plural: clusteraccounttemplates
    singular: clusteraccounttemplate
  preserveUnknownFields: true
  scope: Cluster
  subresources:
    status: {}
  version: v1
  versions:
    - name: v1
      served: true
      storage: true