apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: users.storage.loft.sh
spec:
  conversion:
    strategy: None
  group: storage.loft.sh
  names:
    kind: User
    listKind: UserList
    plural: users
    singular: user
  preserveUnknownFields: true
  scope: Cluster
  subresources:
    status: {}
  version: v1
  versions:
    - name: v1
      served: true
      storage: true
